# -*- coding: utf-8 -*-
"""CV Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7fbohSsseZ1ZkKyLftSVPgQhTHXAHQH
"""

# [Colab Cell 0]
from google.colab import drive
import os

# 1. 将你的 Google Drive 挂载到 Colab 环境中
# 运行后会弹出一个窗口要求你授权，允许即可
drive.mount('/content/drive')

# 2. 在 Colab 本地创建一个工作目录用来存放解压后的数据
!mkdir -p /content/Construction_Safety_Project

# 3. 解压 final.zip (假设你把它直接上传到了 Drive 的根目录下)
# 如果你放在了某个文件夹里，比如 'Colab Notebooks'，请将路径改为 '/content/drive/MyDrive/Colab Notebooks/final.zip'
!unzip -q '/content/drive/MyDrive/final.zip' -d /content/Construction_Safety_Project

# 4. 检查解压是否成功，看看文件是不是都在里面了
!ls -la /content/Construction_Safety_Project

# [Colab Cell 1]
# 安装 Ultralytics 库 (YOLOv8)
!pip install ultralytics -q
import ultralytics
ultralytics.checks() # 检查 GPU 是否正常挂载

# [Colab Cell 2]
from ultralytics import YOLO

# 1. 加载预训练的 YOLOv8-nano 模型（适合边缘部署）
model = YOLO('yolov8n.pt')

# 2. 开始训练
# 请将 'data.yaml' 替换为成员 A 给你的配置文件的实际路径
# 参数说明：epochs 训练轮数, imgsz 图像尺寸, batch 批次大小, device=0 使用GPU
results = model.train(
    data='/content/Construction_Safety_Project/final/construction safety.v2i.yolov8/data.yaml',
    epochs=50,        # 建议先跑 50 轮看看收敛情况，后续可增加到 100-300
    imgsz=640,
    batch=16,
    device=0,
    project='Construction_Safety', # 保存结果的项目文件夹名
    name='yolov8n_baseline'        # 本次实验的名称
)

print("训练完成！模型权重保存在: Construction_Safety/yolov8n_baseline/weights/best.pt")

# [Colab Cell 3]
from ultralytics import YOLO

# 加载你刚才训练好的最优模型
best_model_path = '/content/best (1).pt'
model_to_optimize = YOLO(best_model_path)

# 【实验 A】：导出为 ONNX 格式 (FP32 标准精度)
model_to_optimize.export(format='onnx')

# 【实验 B】：导出为 ONNX 格式 (FP16 半精度量化)
# 这会让模型体积缩小一半，推理速度提升，精度几乎不掉
model_to_optimize.export(format='onnx', half=True)

# 实验 C：导出为 TFLite 格式 (INT8 量化)
# 注意：INT8 量化必须传入 data 配置文件路径来进行数据校准
model_to_optimize.export(
    format='tflite',
    int8=True,
    data='/content/Construction_Safety_Project/final/construction safety.v2i.yolov8/data.yaml'
)
# 提示：在你的最终报告中，你可以列一个表格，对比原模型、FP16 模型、INT8 模型的
# 1. 模型大小 (MB)
# 2. 推理时间 (ms/im)
# 3. mAP50-95 准确率
# 这就是一个非常标准的“消融实验 (Ablation Study)”，能拿高分！

# [Colab Cell 4]
import cv2
import json
from ultralytics import YOLO

class SafetyDetectorAPI:
    def __init__(self, model_path):
        """初始化检测器"""
        self.model = YOLO(model_path)

    def analyze_image(self, image_path):
        """
        接收图片路径，返回结构化的 JSON 数据，供 LLM 分析
        """
        results = self.model(image_path)

        detections = []
        # 提取第一个结果（单张图片）
        for box in results[0].boxes:
            class_id = int(box.cls[0].item())
            class_name = self.model.names[class_id]
            confidence = round(box.conf[0].item(), 3)

            # 获取边界框坐标 [x1, y1, x2, y2]
            coords = box.xyxy[0].tolist()
            coords = [round(c, 1) for c in coords]

            detections.append({
                "object": class_name,
                "confidence": confidence,
                "bounding_box": coords
            })

        # 构建一个供 LLM 消费的 Prompt 上下文
        report = {
            "total_objects_detected": len(detections),
            "details": detections
        }

        return json.dumps(report, indent=4)